services:
  - type: web
    name: clutch-backend
    env: docker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CLOUDFLARE_R2_ACCOUNT_ID
        sync: false
      - key: CLOUDFLARE_R2_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_R2_SECRET_KEY
        sync: false
      - key: CLOUDFLARE_R2_BUCKET
        sync: false
      # Firebase Auth and Firestore env variables
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
